# Generated by Django 5.1.3 on 2024-11-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='comments',
            new_name='description',
        ),
    ]
